### ISSUE TITLE
InfluxDB config template not created

### ISSUE THREAD

**Issue by PoxyDoxy** [Cubxity/UnifiedMetrics#103]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues before opening this bug report.

### Current Behavior

Influx DB Driver .yml file is not created in "/plugins/unifiedmetrics/driver/" folder.
Only "prometheus.yml" is shown.

### Expected Behavior

Config file should be created containing config defaults for using InfluxDB.

### Server type

Fabric

### Server Version

Velocity 1.20.1

### Other Mods / Plugins in your server

- azlink
- bStats
- luckperms
- Negativity
- SlashServer

### Error log

No error log, plugin loaded OK on default config: 
```
[19:25:46 INFO] [unifiedmetrics]: Initializing driver 'prometheus'.
[19:25:46 INFO] [unifiedmetrics]: Driver 'prometheus' initialized (317 ms).
```

**Comment by Cubxity** [comment]
This is not a bug, you're using the prometheus driver. Change the driver in the config file to influxdb and restart.

**Comment by PoxyDoxy** [comment]
Already tried that despite there being no documentation for it.
Logs report `[21:45:09 WARN] [unifiedmetrics]: Driver 'influxdb' not found. Metrics will be enabled when the driver is loaded.`
Most likely because there's no file listed under the driver folder.... just like I had already mentioned in the bug report...

**Comment by Cubxity** [comment]
Use `influx`.

**Comment by PoxyDoxy** [comment]
Also tried that prior to making the bug report, log reports
```
[21:49:49 INFO] [unifiedmetrics]: Initializing driver 'influx'.
[21:49:50 INFO] [unifiedmetrics]: Driver 'influx' initialized (751 ms).
[21:48:42 WARN] [dev.cubxity.plugins.metrics.libs.com.influxdb.client.write.events.WriteRetriableErrorEvent]: The retriable error occurred during writing of data. Reason: 'influxdb: Name or service not known'. Retry in: 8.572s.
```

**Comment by Cubxity** [comment]
You need to configure the influxdb driver configuration.

**Comment by PoxyDoxy** [comment]
Ok, looks like the default config file has generated now containing defaults.
Sorry for wasting your time however was out of ideas when the Influx documentation just says "Todo".
