### ISSUE TITLE
It would be nice to have support for modpacks

### ISSUE THREAD

**Issue by Nukecraft5419** [Cubxity/UnifiedMetrics#111]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hi it would be nice to have support for modpacks i.e. who is a modpack creator like I would like to collect data from modpack users like modpack version Operating System Version, Java Version in use, Launcher, Country from where it is used and also the Client language they use, plus you have higher FPS numbers achieved

### How would you like to see this implemented?

It would be cool to implement it for fabric from 1.8.9 to 1.20.x so all versions of fabric so you can cover everything like my modpack and with the following versions: 1.18.2, 1.19.4, 1.20.1 and in the works 1.20.2, 1.20.3, 1.20. 4 would be handy to be able to monitor everything i.e. RAM, OS, CPU, GPU, Modpack Version, Fabric Version, Java Version, java flags, Minecraft Version, Client Language, State from where it is used, Laucnher used, Highest FPS and Lowest FPS reached let's say like an average of these and also Automatic Crash Reporting so we can help them

### Additional information to this request.

I hope it will be accepted wholeheartedly and a god thing that I know you will surely be able to do, I have improved the things to add in comparison to the description so the functions are put better in the section "How would you like to see this implemented?"

**Comment by Cubxity** [comment]
I'm unsure if UnifiedMetrics is what you're actually looking for. UnifiedMetrics is designed to collect metrics from controlled server environments and not client environments.

**Comment by Nukecraft5419** [comment]
Do you happen to know of one client-side
