### ISSUE TITLE
Support Influx 1.8

### ISSUE THREAD

**Issue by Brain-Gamer** [Cubxity/UnifiedMetrics#12]
This is a bit of an unfortunate situation I'm in..

I would like to get the metrics for Influx 1.8, so no buckets etc. since not all my other metric collectors are ready to upgrade to Influx 2.x

I guess one could solve this by using UnifiedMetrics in Prometheus "mode" once that is implemented and then use telegraf to grab the Prometheus data for collection to Influx 1.8

Or is there already support for the "old" Influx 1.8 behaviour?

**Comment by Cubxity** [comment]
UnifiedMetric *should* work with Influx 1.x. Are you able to try it out?

**Comment by Brain-Gamer** [comment]
how would I configure it to do so? the documentation on the driver configuration is a bit lacking

**Comment by Cubxity** [comment]
No, I don't you you need to do anything special with the configuration. Just enter the URL and optionally credentials for your InfluxDB server.

**Comment by Brain-Gamer** [comment]
but how do I define the name of my database then?

**Comment by Cubxity** [comment]
a "bucket" is considered a "database" iirc

**Comment by Cubxity** [comment]
Any updates regarding this matter?

**Comment by Brain-Gamer** [comment]
no sorry, didnt get to test it out yet. I will update once I did.

**Comment by portlek** [comment]
i've just triend on 1.8, its completely working for me
![image](https://user-images.githubusercontent.com/12835420/111804386-166a0c80-88e1-11eb-9a12-5096bd703a58.png)

**Comment by Cubxity** [comment]
Closing the issue due to it not being an issue.
