### ISSUE TITLE
Flux support(influxdb 2.x)

### ISSUE THREAD

**Issue by portlek** [Cubxity/UnifiedMetrics#19]

**Comment by Cubxity** [comment]
Are you able to describe the issue further?

**Comment by portlek** [comment]
- Grafana Influx dashboard for Flux syntax.

**Comment by portlek** [comment]
actually, there should be only Grafana dashboard support for flux syntax, nothing else.

**Comment by Cubxity** [comment]
Closing due to it not being directly related with UnifiedMetrics.
