### ISSUE TITLE
InfluxDB v2 configuration

### ISSUE THREAD

**Issue by tigattack** [Cubxity/UnifiedMetrics#24]
I see InfluxDB v2 support was added/fixed in a pre-release a month ago, but an InfluxDB v2 configuration guide is not yet available.

There's not many differences, as I'm sure you're aware, but some notes for v2 in the current Influx driver wiki page would be helpful.

The main thing I'm wondering is how I can specify the token? This option doesn't seem to work since, if specified, some `influx.toml` fields (notably username and password) are reset to default on start.  
Also, how does it know whether to use the `/api/v2` endpoint or not?

Does this even truly support InfluxDB v2, or should [v1 auth compatibility](https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/v1/auth/) and [DBRP mappings](https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/v1/dbrp/) be used when running v2?

**Comment by Cubxity** [comment]
The configuration issue has been fixed in the latest release. I'll further investigate on how UM interacts with InfluxDB 2.x. Though the wiki page demonstrates how to set up UM with InfluxDB 2.x using Docker.

**Comment by tigattack** [comment]
The InfluxDB v2 API uses token-based authentication, so I'm unsure how username/password auth would work, unless I'm missing something.

I've not had any luck getting it to work yet, using the development release from March 26th.

**Comment by Cubxity** [comment]
Hm, I'll check it out later today. Feel free to add me on Discord (Cubxity#7801) if you want support.

**Comment by tigattack** [comment]
Thanks, much appreciated. I've added you.

**Comment by reepje123** [comment]
> The InfluxDB v2 API uses token-based authentication, so I'm unsure how username/password auth would work, unless I'm missing something.
> 
> I've not had any luck getting it to work yet, using the development release from March 26th.

After running into the same issue already using InfluxDB 2.0 myself I've found out that using 2.0 works just fine as long as admin credentials are being used. The alternative would be using telegraf to scrape the prometheus metrics and exporting them to InfluxDB v2.

**Comment by tigattack** [comment]
Thanks. Neither of these workarounds are ideal but they are at least functional until Influx2 support is implemented.

**Comment by Cubxity** [comment]
InfluxDB 2 support will be implemented properly in 0.3.x

**Comment by tigattack** [comment]
Thanks! Happy to try out any dev builds or betas.

**Comment by Cubxity** [comment]
Implemented in 93557034e36ffef0f7388f58d8473a4bdad95bf1. Do note that 0.3.x includes breaking changes and uses YAML instead of TOML.
