### ISSUE TITLE
Spigot 1.17 - java.lang.IllegalStateException: Asynchronous Chunk getEntities call

### ISSUE THREAD

**Issue by josephcy95** [Cubxity/UnifiedMetrics#26]
Doesn't work with 1.17 spigot and any 1.17 fork, gives below error:

> java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
> at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[patched_1.17.jar:git-Tuinity-"8482a76"]
> at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:2318) ~[patched_1.17.jar:git-Tuinity-"8482a76"]
> at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getEntities(CraftWorld.java:1172) ~[patched_1.17.jar:git-Tuinity-"8482a76"]
> at dev.cubxity.plugins.metrics.bukkit.metric.world.WorldCollector.collect(WorldCollector.kt:33) ~[?:?]
> at dev.cubxity.plugins.metrics.api.metric.MetricKt.collect(Metric.kt:40) ~[?:?]
> at dev.cubxity.plugins.metrics.api.metric.MetricsManagerKt.collect(MetricsManager.kt:38) ~[?:?]
> at dev.cubxity.plugins.metrics.influx.InfluxMetricsDriver$scheduleTasks$1.run(InfluxMetricsDriver.kt:68) ~[?:?]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
> at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
> at java.lang.Thread.run(Thread.java:831) [?:?]

Appreciate if you could update it to work with latest version, thanks!

**Comment by Cubxity** [comment]
Fixed in 4544e1a10d3cdb1c29ec2f227c3ac0bc3cdb5268
