### ISSUE TITLE
Magma Support / java 8

### ISSUE THREAD

**Issue by SkyLightEffect** [Cubxity/UnifiedMetrics#32]
Hey, would it be possible to build the project with java 8? Unfortunately, Magma does only support java 8.

**Comment by Cubxity** [comment]
Yes, it should be possible. UnifiedMetrics itself targets java 8 and above. However, you cannot build other subprojects like bukkit or velocity due to the dependencies targeting Java 16 and 11.

**Comment by SkyLightEffect** [comment]
Yeah, I need the bukkit subproject. Thanks for your help!
