### ISSUE TITLE
TPS not being reported and TPS/MSPT graphs not working

### ISSUE THREAD

**Issue by NielsjeNL** [Cubxity/UnifiedMetrics#49]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues before opening this bug report.

### Current Behavior

Hi all.

Neat plugin you have here. The visualization in Grafana is great and it was easy to set up.

I'm running into a bug where the TPS (Mean) value is not being reported at all, and the TPS and MSPT graphs are empty:
![image](https://user-images.githubusercontent.com/16190752/144709152-7a916edc-4c1d-4315-932b-510d57b79c69.png)

All UnifiedMetrics configs were left to their default values.
I tried looking into the reporting endpoint manually but didn't really understand the data, or possibly some data was missing.

### Expected Behavior

The TPS (Mean value) should be updated with the server's live TPS.
The graphs should be updated with the correct data.

### Server type

Fabric

### Server Version

1.18

### Other Mods / Plugins in your server

Bluemap
Fabric API 0.43.1 + 1.18
Fabric Language Kotlin 1.6.4 + Kotlin 1.5.30
LazyDFU 0.1.2
NotEnoughCrashes 4.1.3

**Comment by Cubxity** [comment]
Please try 0.3.4-SNAPSHOT

**Comment by NielsjeNL** [comment]
Yep, running 0.3.4-SNAPSHOT fixed it. Thanks for the quick reply!
