### ISSUE TITLE
Grafana dashboard - wrong metric for Daemons graph

### ISSUE THREAD

**Issue by h1kkan** [Cubxity/UnifiedMetrics#50]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues before opening this bug report.

### Current Behavior

_**Treads**_ and _**Daemons**_ graphs currently displays same metric `jvm_threads_current_count`

### Expected Behavior

_**Treads**_ graph should display `jvm_threads_current_count`, _**Daemons**_ graph should display `jvm_threads_daemon_count`

**Comment by Cubxity** [comment]
Fixed [here](https://grafana.com/grafana/dashboards/14756)
