### ISSUE TITLE
Minestom NoSuchMethodError (getUpdateManager)

### ISSUE THREAD

**Issue by LBuke** [Cubxity/UnifiedMetrics#54]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues before opening this bug report.

### Current Behavior

On the latest Minestom build, `MinecraftServer.getUpdateManager()` has been removed thus throwing NSME.
(_com.github.Minestom:Minestom:5b699e0375_)

### Expected Behavior

TickCollection.kt updated and not throwing NSME

### Server type

Minestom

### Server Version

1.18.1

### Other Mods / Plugins in your server

None.

### Error log

`WARN - An error occurred whilst registering metric: java.lang.NoSuchMethodError: 'net.minestom.server.UpdateManager net.minestom.server.MinecraftServer.getUpdateManager()'`

**Full stack trace:**
https://www.toptal.com/developers/hastebin/odomoqurac.properties

**Comment by Cubxity** [comment]
Fixed in https://github.com/Cubxity/UnifiedMetrics/commit/5f6da83406b400de642a339f1a9795e5fb8e7ce6
