### ISSUE TITLE
Config reset to default after plugin load

### ISSUE THREAD

**Issue by CryPt00n** [Cubxity/UnifiedMetrics#9]
Hi,

the UM config is being reset to default every time after i started the server. So i have to enter it every time before restarting the server. Also when my influxdb docker is restarting, it looses connection and seems to reload the default config then and crashing the server due this.

**Comment by Cubxity** [comment]
Hi,
Thanks for the report. I'm looking into it right now. Though the plugin shouldn't crash the server.

**Comment by Cubxity** [comment]
@CryPt00n I've pushed a new commit addressing this issue.

The config for InfluxDB will load from `UnifiedMetrics/driver/influx.toml` instead.

Example:
```
[influx]
url = "http://influxdb:8086"
bucket = "unifiedmetrics"
influx = "influx"
password = "influx"
interval = 10
```

**Comment by Cubxity** [comment]
The latest build will be available at https://github.com/Cubxity/UnifiedMetrics/releases/tag/latest

**Comment by CryPt00n** [comment]
Tried the new build, entered the informations the following:
config.toml
```
[server]
server = "main"

[metrics]
enabled = true
driver = "influx"
```

influx.toml
```
[metrics.influx]
url = "http://bla.bla.bla:8086"
bucket = "minecraftdata"
interval = 10 # Interval in seconds
```

Now both files get reset after starting the server, and the plugin is no longer working. Also the server is crashing. 
I´ve attached you the error message from the logs. 

[Log.txt](https://github.com/Cubxity/UnifiedMetrics/files/6022094/Log.txt)

**Comment by Cubxity** [comment]
@CryPt00n remove `metrics.` from the table header. Look at the example.

**Comment by CryPt00n** [comment]
Ahk sorry. My fault. Fixed it.

But now the plugin wont start due the update check:

`[14:54:31] [Server thread/ERROR]: Error occurred while enabling UnifiedMetrics v0.1.2 (Is it up to date?)`

**Comment by Cubxity** [comment]
@CryPt00n there's no update check in the plugin. Can you send the stacktrace? If you wish you can reach me out on Discord (Cubxity#7801).

**Comment by Cubxity** [comment]
Resolved. 

Note: No changes are required to username/password for no authentication.
